import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import MenuLateral from '@/components/template/MenuLateral'
import Cabecalho from '@/components/template/Cabecalho'
import Conteudo from '@/components/template/Conteudo'
import useAppData from '@/data/hook/useAppData'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //const { tema } = useAppData()
  const tema = ''
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`${tema} flex h-screen w-screen`}>
          <MenuLateral />
          <div className={`
                flex flex-col w-full p-7 
                bg-gray-300 dark:bg-gray-800
            `}>
            <Cabecalho titulo={'Menu Inicial'} subtitulo={'Estamos construindo um template Admin!'} />
            <Conteudo>
              {children}
            </Conteudo>
          </div>
        </div>
      </body>
    </html>
  )
}
