exports.seed = function(knex) {
    // Deletes ALL existing entries
    knex('categories').where('id', '>', 100).del()
        .then(function() {
            return knex('categories').del()
                .then(function() {
                    // Inserts seed entries
                    return knex('categories').insert([
                        { id: 01, name: 'Grupos de aborto/defesa', description: 'Sites que contêm informações ou argumentos prós ou contra o aborto, por exemplo, métodos abortivos, dicas para prevenção ou prática de aborto, efeitos ou a falta de efeitos do ato.' },
                        { id: 02, name: 'Conteúdo adulto/maduro', description: 'Sites que contêm informações ou argumentos prós ou contra o aborto, por exemplo, métodos abortivos, dicas para prevenção ou prática de aborto, efeitos ou a falta de efeitos do ato.' },
                        { id: 03, name: 'Anúncios', description: 'Sites com anúncios ou banners on-line sempre serão permitidos. Esses não incluem servidores de anúncios com mensagens específicas para adultos.' },
                        { id: 04, name: 'Álcool/tabaco', description: 'Sites que promovem ou oferecem produtos de álcool/tabaco, ou apresentam os meios para sua produção. Inclui os que defendem, recomendam ou encorajam o consumo. Mas não contém aqueles que vendem produtos que usam álcool ou tabaco como subcomponentes.' },
                        { id: 05, name: 'Artes/entretenimento', description: 'Sites que promovem e informam sobre filmes, vídeos, televisão, músicas e guias de programação, livros, quadrinhos, cinemas, galerias, artistas ou avaliações de entretenimento.' },
                        { id: 06, name: 'Negócios/economia', description: 'Sites dedicados a empresas, informações de negócios, economia, marketing, administração e empreendedorismo. Não inclui sites que oferecem serviços definidos em outra categoria (por exemplo, de empresas de tecnologia da informação ou que vendem serviços de viagem).' },
                        { id: 07, name: 'Chat/mensagens instantâneas', description: 'Sites que disponibilizam recursos de bate-papo ou mensagens instantâneas, ou downloads para clientes.' },
                        { id: 08, name: 'Culto/ocultismo', description: 'Sites que promovem ou oferecem métodos, meios de instrução ou outros recursos para afetar ou influenciar eventos reais usando feitiços, maldições, poderes mágicos ou seres sobrenaturais.' },
                        { id: 09, name: 'Instituições culturais', description: 'Sites patrocinados por instituições culturais ou com informações sobre museus, galerias e teatros (não incluem cinemas). Inclui grupos como 4-H e Boy Scouts of America.' },
                        { id: 10, name: 'Drogas/drogas ilícitas', description: 'Sites que promovem, oferecem, vendem, fornecem, encorajam ou defendem de alguma forma o uso recreativo ou ilegal, o cultivo, a fabricação ou a distribuição de drogas, produtos farmacêuticos, plantas ou produtos químicos tóxicos e toda parafernália associada. Contém também sites que abordam ou promovem o uso e o abuso de drogas controladas, e seus equipamentos associados, além dos que informam sobre drogas aprovadas e seu uso medicinal, e promovem a utilização de produtos químicos que não são regulados pelo FDA.' },
                        { id: 11, name: 'Educação', description: 'Sites educativos e de educação à distância, e que comercializam informações ou programas escolares. Inclui os sites patrocinados por escolas, instituições de ensino e grupos de professores ou alunos.' },
                        { id: 12, name: 'E-mail', description: 'Sites que oferecem serviços de webmail, como leitura de e-mails, e-cards e serviços de lista de endereçamento on-line.' },
                        { id: 13, name: 'Para crianças', description: 'Sites projetados especialmente para crianças.' },
                        { id: 14, name: 'Downloads de freeware/software', description: 'Sites dedicados a download eletrônico de pacotes de software, pagos ou não.' },
                        { id: 15, name: 'Jogos de azar', description: 'Sites em que o usuário pode fazer apostas ou participar de grupos de apostas (inclusive loterias) on-line. Inclui os que fornecem informações, assistência, recomendações ou treinamento sobre como fazer apostas ou participar de jogos de azar. Não inclui sites de hotéis ou cassinos off-line (quando não se enquadram nos requisitos acima), ou os que comercializam produtos ou máquinas associados.' },
                        { id: 16, name: 'Jogos', description: 'Sites que contêm informações ou que apoiam jogos de azar ou que têm downloads de videogames, jogos de computador, jogos eletrônicos, dicas e conselhos sobre jogos ou sobre como obter cheat codes. Também inclui sites dedicados à venda de jogos de tabuleiro, bem como publicações e revistas dedicadas a jogos. Inclui sites que ofereçam suporte ou hospedem sorteios e brindes on-line.' },
                        { id: 17, name: 'Órgãos governamentais', description: 'Sites patrocinados por (ou que fornecem informações sobre) governos, agências governamentais e serviços públicos, como tributação e serviços emergenciais. Inclui também sites que abordam ou explicam leis de diversas agências governamentais.' },
                        { id: 18, name: 'Sistemas de invasão/evasão de proxy', description: 'Sites que contêm informações sobre o acesso ou uso ilegal ou questionável de equipamentos de comunicação/software, ou ensinam a como driblar os recursos do servidor proxy ou obter acesso a URLs ignorando o servidor proxy.' },
                        { id: 19, name: 'Integridade', description: 'Sites que fornecem conselhos e informações sobre saúde em geral, por exemplo, fitness e bem-estar, saúde pessoal ou serviços médicos, medicamentos, terapias alternativas e complementares, informações médicas sobre alimentos, odontologia, optometria, psiquiatria geral, autoajuda e organizações de assistência dedicadas a uma determinada doença ou quadro de saúde.' },
                        { id: 20, name: 'Humor/piadas', description: 'Sites especializados em humor, comédia, piadas e coisas divertidas. Pode incluir sites com humor ou piadas de conteúdo adulto. Sites de materiais para adultos também podem ter a classificação de categoria Conteúdo adulto/maduro.' },
                        { id: 21, name: 'Habilidades ilegais/questionáveis', description: 'Sites que defendem ou recomendam a prática de atos ilegais, como roubo de serviços, fuga à aplicação da lei, fraude, técnicas de furto e infração de direitos autorais. Também inclui sites que forneçam ou vendam materiais educacionais questionáveis, como trabalhos de conclusão de curso.' },
                        { id: 22, name: 'Tecnologia da informação/computadores', description: 'Sites que patrocinam ou fornecem informações sobre computadores, tecnologia, internet e organizações e empresas relacionadas à tecnologia.' },
                        { id: 23, name: 'Leilões virtuais', description: 'Sites que dão suporte à oferta e compra de bens entre pessoas. Não inclui anúncios classificados.' },
                        { id: 24, name: 'Internet Watch Foundation CAIC', description: 'Sites que a Internet Watch Foundation considera detentores de materiais potencialmente criminosos para Internet, incluindo conteúdos de abuso sexual de crianças hospedados em qualquer parte do globo, materiais obscenos e ilegais para adultos hospedados no Reino Unido (RU) e imagens não fotográficas de pedofilia hospedadas no RU.' },
                        { id: 25, name: 'Roupas íntimas/trajes de banho', description: 'Sites com imagens ou ofertas de trajes de banho, roupas íntimas ou outros tipos de roupas sugestivas. Não inclui sites que vendam roupas íntimas como uma subseção de outros produtos oferecidos.' },
                        { id: 26, name: 'Busca de empregos', description: 'Sites que fornecem assistência à descoberta de vagas e ferramentas para localização de potenciais empregadores.' },
                        { id: 27, name: 'Malware', description: 'Sites que hospedam softwares que se transferem dissimuladamente para o sistema do usuário com o objetivo de coletar informações e monitorar as atividades do usuário. Inclui também sites infectados por softwares destrutivos ou mal-intencionados como vírus, cavalos de troia ou worms especificamente projetados para danificar, interferir, atacar ou manipular sistemas de computadores sem o consentimento do usuário.' },
                        { id: 28, name: 'Exército', description: 'Sites que promovem ou fornecem informações sobre unidades militares ou serviços armados.' },
                        { id: 29, name: 'Multimídia', description: 'Sites que vendem, entregam ou transmitem por streaming música ou vídeo em um formato qualquer, incluindo aqueles que disponibilizam downloads para seus visualizadores.' },
                        { id: 30, name: 'Notícias/mídia', description: 'Sites dedicados principalmente ao fornecimento de informações ou comentários sobre eventos atuais ou questões contemporâneas. Também inclui estações de rádio e revistas. Não inclui sites que possam ser classificados em outras categorias.' },
                        { id: 31, name: 'Não classificado', description: 'Sites não revisados e classificados porque não receberam visualizações registradas ou porque o número de visualizações é extremamente baixo. Os clientes podem enviar uma solicitação para que a classificação de uma URL no banco de dados do Dell SonicWALL Content Filtering seja reavaliada ou para que uma URL previamente desconhecida seja classificada e adicionada ao banco de dados.' },
                        { id: 32, name: 'Nudismo', description: 'Sites com representações do corpo humano nu ou seminu. Essas representações não são necessariamente sexuais na intenção ou no efeito, podendo abranger sites contendo pinturas de nus ou galerias de fotos de natureza artística. Essa categoria também inclui sites nudistas ou naturalistas contendo fotos de pessoas nus.' },
                        { id: 33, name: 'Bancos on-line', description: 'Sites que oferecem ou promovem serviços bancários (on-line ou off-line) ou outros tipos de informações financeiras, como empréstimos. Não inclui sites que oferecem informações do mercado, corretagem ou serviços de transações.' },
                        { id: 34, name: 'Corretagem/transação on-line', description: 'Sites que fornecem ou promovem comércio de valores mobiliários e gestão de ativos de investimento (on-line ou off-line). Inclui também sites de seguros, além dos que oferecem estratégias, cotações e notícias de investimentos financeiros.' },
                        { id: 35, name: 'Pay to Surf', description: 'Sites que pagam usuários em dinheiro ou em prêmios para que cliquem ou leiam links, e-mails ou páginas da Web específicos.' },
                        { id: 36, name: 'Encontros e namoros', description: 'Sites que promovem relacionamentos interpessoais.' },
                        { id: 37, name: 'Política e grupos de defesa', description: 'Sites que divulgam informações sobre ou sejam patrocinados por partidos políticos, grupos com interesses específicos ou qualquer organização que defenda mudanças ou reformas na política pública, de opinião popular, nos comportamentos sociais ou nas atividades econômicas.' },
                        { id: 38, name: 'Pornografia', description: 'Sites que contêm sexo explícito com o propósito de despertar interesse sexual ou lascivo.' },
                        { id: 39, name: 'Setor imobiliário', description: 'Sites sobre compra, venda e locação de imóveis ou propriedades.' },
                        { id: 40, name: 'Referência', description: 'Sites que contêm referências pessoais, profissionais ou educacionais, além de dicionários on-line, mapas, censo, almanaques, catálogos de biblioteca, sites relacionados à genealogia e informações científicas.' },
                        { id: 41, name: 'Religião', description: 'Sites que promovem ou divulgam religiões, tradicionais ou não, ou assuntos relacionados à religião, além de igrejas, sinagogas e outros locais de adoração. Não inclui sites sobre feitiçaria (Culto/ocultismo) ou crenças ateístas.' },
                        { id: 42, name: 'Restaurantes e comidas', description: 'Sites que listam, avaliam, discutem, anunciam e promovem alimentos, serviços de bufê, serviços de restaurante, culinária e receitas.' },
                        { id: 43, name: 'Mecanismos de pesquisa e portais', description: 'Sites que dão suporte a pesquisas na internet, índices e diretórios.' },
                        { id: 44, name: 'Educação sexual', description: 'Sites que contêm material gráfico sobre reprodução, desenvolvimento sexual, práticas de sexo seguro, sexualidade, controle de natalidade e desenvolvimento sexual. Também inclui sites que oferecem dicas para uma melhor vida sexual, bem como produtos usados para intensificação do prazer sexual.' },
                        { id: 45, name: 'Comércio', description: 'Sites que fornecem ou anunciam maneiras de obter bens ou serviços. Não inclui sites que possam ser enquadrados em outras categorias, como veículos ou armas.' },
                        { id: 46, name: 'Redes sociais', description: 'Comunidades e sites que permitem a interação entre usuários, a publicação de mensagens, imagens ou outros tipos de comunicação com grupos de pessoas. Não inclui blogs ou sites pessoais.' },
                        { id: 47, name: 'Sociedade e estilo de vida', description: 'Sites que fornecem informações de assuntos relacionados ao dia a dia. Não inclui aqueles que podem ser enquadrados em outras categorias, como artes e entretenimento, saúde e esportes/recreação.' },
                        { id: 48, name: 'Esportes/recreação', description: 'Sites que promovem ou fornecem informações sobre esportes para espectadores, atividades recreativas ou hobbies. Inclui sites que discutem ou informam sobre camping, jardinagem e coleções.' },
                        { id: 49, name: 'Viagens', description: 'Sites que promovem ou oferecem oportunidades de planejamento de viagens, incluindo busca e reservas de viagem, locação de veículos, descrição de destinos ou promoções de hotéis e cassinos.' },
                        { id: 50, name: 'Grupos de notícias Usenet', description: 'Sites que oferecem acesso a grupos de notícias Usenet ou outros sistemas de mensagens ou BBS.' },
                        { id: 51, name: 'Veículos', description: 'Sites que abordam ou promovem informações sobre veículos, barcos ou aeronaves. Inclui os sites que apoiam o comércio on-line de veículos ou peças.' },
                        { id: 52, name: 'Violência, ódio e racismo', description: 'Sites com representações de lesões corporais ou danos à propriedade muito graves, que defendem ou dão dicas sobre como causar tais atos. Inclui também aqueles que defendem ou contêm representações de hostilidade, incitam agressão ou denigrem pessoas ou grupos por causa de raça, religião, gênero, nacionalidade, origem étnica ou outros aspectos involuntários.' },
                        { id: 53, name: 'Armas', description: 'Sites que vendem, analisam ou descrevem armas de fogo, facas ou equipamentos de artes marciais e seus acessórios, ou apresentam informações sobre a sua utilização ou outras modificações. Não inclui sites de colecionadores ou que defendem ou se opõem ao desarmamento.' },
                        { id: 54, name: 'Comunicações na Web', description: 'Sites que permitem ou oferecem comunicação baseada na Web via e-mail, chat, mensagens instantâneas ou quadros de mensagens.' },
                        { id: 55, name: 'Hospedagem na Web', description: 'Sites de organizações que fornecem páginas de domínio de nível superior, além de comunidades da Web ou serviços de hospedagem.' }
                    ]);
                });
        });
};