import { db } from "./db";

export async function populateUrl() {
    await db.url.bulkAdd([
        { id: 1, url: 'www.gynpages.com', categories: [], ages: [] },
        { id: 2, url: 'www.abortionfacts.com', categories: [], ages: [] },
        { id: 3, url: 'www.humorbomb.org', categories: [], ages: [] },
        { id: 4, url: 'www.steakandcheese.com', categories: [], ages: [] },
        { id: 5, url: 'www.punchbaby.com', categories: [], ages: [] },
        { id: 6, url: 'www.adblade.com', categories: [], ages: [] },
        { id: 7, url: 'www.netvert.biz', categories: [], ages: [] },
        { id: 8, url: 'www.budweiser.com', categories: [], ages: [] },
        { id: 9, url: 'www.coors.com', categories: [], ages: [] },
        { id: 10, url: 'www.imdb.com', categories: [], ages: [] },
        { id: 11, url: 'www.eonline.com', categories: [], ages: [] },
        { id: 12, url: 'www.moviephone.com', categories: [], ages: [] },
        { id: 13, url: 'www.ge.com', categories: [], ages: [] },
        { id: 14, url: 'www.sunbeam.com', categories: [], ages: [] },
        { id: 15, url: 'www.web.icq.com/icqchat', categories: [], ages: [] },
        { id: 16, url: 'www.aim.com', categories: [], ages: [] },
        { id: 17, url: 'www.messenger.msn.com', categories: [], ages: [] },
        { id: 18, url: 'www.phlums.com', categories: [], ages: [] },
        { id: 19, url: 'www.terrificator.com', categories: [], ages: [] },
        { id: 20, url: 'www.childmuseum.org', categories: [], ages: [] },
        { id: 21, url: 'www.scouting.org', categories: [], ages: [] },
        { id: 22, url: 'www.4h.org', categories: [], ages: [] },
        { id: 23, url: 'www.marijuana.org', categories: [], ages: [] },
        { id: 24, url: 'www.hightimes.com', categories: [], ages: [] },
        { id: 25, url: 'www.education-world.com', categories: [], ages: [] },
        { id: 26, url: 'www.ed.govwww.nyu.edu', categories: [], ages: [] },
        { id: 27, url: 'www.email.com', categories: [], ages: [] },
        { id: 28, url: 'www.hotmail.com', categories: [], ages: [] },
        { id: 29, url: 'www.yahooligans.com', categories: [], ages: [] },
        { id: 30, url: 'www.kidsites.com', categories: [], ages: [] },
        { id: 31, url: 'www.panwapa.com', categories: [], ages: [] },
        { id: 32, url: 'www.download.com', categories: [], ages: [] },
        { id: 33, url: 'www.tucows.com', categories: [], ages: [] },
        { id: 34, url: 'www.gambling.com', categories: [], ages: [] },
        { id: 35, url: 'www.casino.com', categories: [], ages: [] },
        { id: 36, url: 'www.sportsbook.com', categories: [], ages: [] },
        { id: 37, url: 'www.nintendo.com', categories: [], ages: [] },
        { id: 38, url: 'www.gamespot.com', categories: [], ages: [] },
        { id: 39, url: 'www.gamesdomain.com', categories: [], ages: [] },
        { id: 40, url: 'www.whitehouse.gov', categories: [], ages: [] },
        { id: 41, url: 'www.federalreserve.gov', categories: [], ages: [] },
        { id: 42, url: 'www.anonymizer.com', categories: [], ages: [] },
        { id: 43, url: 'astalavista.box.sk', categories: [], ages: [] },
        { id: 44, url: 'www.happyhacker.org', categories: [], ages: [] },
        { id: 45, url: 'www.phreak.com', categories: [], ages: [] },
        { id: 46, url: 'www.cvs.com', categories: [], ages: [] },
        { id: 47, url: 'www.webmd.com', categories: [], ages: [] },
        { id: 48, url: 'www.ahajokes.com', categories: [], ages: [] },
        { id: 49, url: 'www.comedycentral.com', categories: [], ages: [] },
        { id: 50, url: 'www.the-jokes.com', categories: [], ages: [] },
        { id: 51, url: 'www.antiessays.com', categories: [], ages: [] },
        { id: 52, url: 'www.monkeysnatcher.com', categories: [], ages: [] },
        { id: 53, url: 'www.dell.com', categories: [], ages: [] },
        { id: 54, url: 'www.microsoft.com', categories: [], ages: [] },
        { id: 55, url: 'www.javaworld.com', categories: [], ages: [] },
        { id: 56, url: 'www.bidfind.com', categories: [], ages: [] },
        { id: 57, url: 'www.ebay.com', categories: [], ages: [] },
        { id: 58, url: 'wovusej.com', categories: [], ages: [] },
        { id: 59, url: 'xujoket.com', categories: [], ages: [] },
        { id: 60, url: 'www.victoriassecret.com', categories: [], ages: [] },
        { id: 61, url: 'www.fredericks.com', categories: [], ages: [] }
    ])
}